apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytest
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: pytest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pytest
      {{- if .Values.metrics.enabled }}
      annotations:
        {{- toYaml .Values.metrics.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pytest
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
      volumes:
        - name: {{ .Values.volume.name }}
          emptyDir: {}
